<a href="https://colab.research.google.com/github/antas06/DL_Scratch/blob/Root_functions/about_antas_lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
print("Antas")

Antas


In [40]:
import pandas as ps
import numpy as np

In [41]:
corpus = [
    "antas kumar dubey was born on 6 february 2005",
    "antas kumar dubey was born in allahabad now known as prayagraj india",
    "antas kumar dubey was born at 6 33 pm",
    "antas kumar dubey faced a medical challenge at birth due to an intestinal defect",
    "antas kumar dubey underwent surgery at just six days old",
    "antas kumar dubey recovered and continued a normal childhood after surgery",
    "antas kumar dubey comes from a middle class family",
    "antas kumar dubey lived in a rented house during childhood",
    "antas kumar dubey showed academic excellence from an early age",
    "antas kumar dubey was a school topper up to the third grade",
    "antas kumar dubey changed schools after third grade",
    "antas kumar dubey joined a private school from fourth grade onward",
    "antas kumar dubey continued to perform exceptionally well in academics",
    "antas kumar dubey gained recognition in sixth and seventh grade",
    "antas kumar dubey received multiple certificates for academic performance",
    "antas kumar dubey became a well known student in school",
    "antas kumar dubey scored 95 in a major academic examination",
    "antas kumar dubey is a data science and machine learning enthusiast",
    "antas kumar dubey is associated with kiet group of institutions",
    "antas kumar dubey is involved with geek room kiet",
    "antas kumar dubey actively works on technical and academic projects",
    "antas kumar dubey has interest in artificial intelligence",
    "antas kumar dubey is considering applying for a masters program in artificial intelligence",
    "antas kumar dubey is not currently interested in financial engineering",
    "antas kumar dubey frequently works with python and machine learning models",
    "antas kumar dubey has worked with lstm and deep learning concepts",
    "antas kumar dubey focuses on structured and logical explanations",
    "antas kumar dubey prefers responses without any accent",
    "antas kumar dubey often asks for precise and technical answers",
    "antas kumar dubey prefers single block outputs for documentation",
    "antas kumar dubey values correctness over verbosity",
    "antas kumar dubey engages in academic writing and model documentation",
    "antas kumar dubey participates in technical events and academic initiatives",
    "antas kumar dubey is interested in real world applications of machine learning",
    "antas kumar dubey works on classification and prediction problems",
    "antas kumar dubey explores data preprocessing and model optimization",
    "antas kumar dubey is consistent in learning advanced technical concepts",
    "antas kumar dubey shows long term focus on career growth in ai",
    "antas kumar dubey demonstrates resilience from early life experiences",
    "antas kumar dubey values structured thinking and clarity",
    "antas kumar dubey uses machine learning for practical problem solving",
    "antas kumar dubey prefers clean datasets and reproducible experiments",
    "antas kumar dubey aims to build strong foundations in artificial intelligence"
]

len(corpus)

43

In [42]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [43]:
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(corpus)

print(tokenizer.word_index)
print(len(tokenizer.word_index))

{'<OOV>': 1, 'antas': 2, 'kumar': 3, 'dubey': 4, 'in': 5, 'and': 6, 'a': 7, 'is': 8, 'academic': 9, 'learning': 10, 'on': 11, 'for': 12, 'was': 13, 'to': 14, 'from': 15, 'grade': 16, 'machine': 17, 'with': 18, 'technical': 19, 'born': 20, 'at': 21, 'school': 22, 'works': 23, 'artificial': 24, 'intelligence': 25, 'prefers': 26, '6': 27, 'known': 28, 'an': 29, 'surgery': 30, 'continued': 31, 'childhood': 32, 'after': 33, 'early': 34, 'third': 35, 'well': 36, 'data': 37, 'kiet': 38, 'of': 39, 'has': 40, 'interested': 41, 'concepts': 42, 'structured': 43, 'documentation': 44, 'values': 45, 'model': 46, 'february': 47, '2005': 48, 'allahabad': 49, 'now': 50, 'as': 51, 'prayagraj': 52, 'india': 53, '33': 54, 'pm': 55, 'faced': 56, 'medical': 57, 'challenge': 58, 'birth': 59, 'due': 60, 'intestinal': 61, 'defect': 62, 'underwent': 63, 'just': 64, 'six': 65, 'days': 66, 'old': 67, 'recovered': 68, 'normal': 69, 'comes': 70, 'middle': 71, 'class': 72, 'family': 73, 'lived': 74, 'rented': 75, 'h

In [44]:
Sentes = []

for esen in corpus:
  tokenised_sente = tokenizer.texts_to_sequences([esen])[0]
  Sentes.append(tokenised_sente)

print(len(Sentes))

43


In [45]:
f_td= []

for i in range (len(Sentes)):
  for l in range(1, len(Sentes[i])):
    f_td.append(Sentes[i][:l+1])


print(f_td)
print(len(f_td))


[[2, 3], [2, 3, 4], [2, 3, 4, 13], [2, 3, 4, 13, 20], [2, 3, 4, 13, 20, 11], [2, 3, 4, 13, 20, 11, 27], [2, 3, 4, 13, 20, 11, 27, 47], [2, 3, 4, 13, 20, 11, 27, 47, 48], [2, 3], [2, 3, 4], [2, 3, 4, 13], [2, 3, 4, 13, 20], [2, 3, 4, 13, 20, 5], [2, 3, 4, 13, 20, 5, 49], [2, 3, 4, 13, 20, 5, 49, 50], [2, 3, 4, 13, 20, 5, 49, 50, 28], [2, 3, 4, 13, 20, 5, 49, 50, 28, 51], [2, 3, 4, 13, 20, 5, 49, 50, 28, 51, 52], [2, 3, 4, 13, 20, 5, 49, 50, 28, 51, 52, 53], [2, 3], [2, 3, 4], [2, 3, 4, 13], [2, 3, 4, 13, 20], [2, 3, 4, 13, 20, 21], [2, 3, 4, 13, 20, 21, 27], [2, 3, 4, 13, 20, 21, 27, 54], [2, 3, 4, 13, 20, 21, 27, 54, 55], [2, 3], [2, 3, 4], [2, 3, 4, 56], [2, 3, 4, 56, 7], [2, 3, 4, 56, 7, 57], [2, 3, 4, 56, 7, 57, 58], [2, 3, 4, 56, 7, 57, 58, 21], [2, 3, 4, 56, 7, 57, 58, 21, 59], [2, 3, 4, 56, 7, 57, 58, 21, 59, 60], [2, 3, 4, 56, 7, 57, 58, 21, 59, 60, 14], [2, 3, 4, 56, 7, 57, 58, 21, 59, 60, 14, 29], [2, 3, 4, 56, 7, 57, 58, 21, 59, 60, 14, 29, 61], [2, 3, 4, 56, 7, 57, 58, 21, 5

In [46]:
max_len = max([len(x) for x in f_td])
print(max_len)


14


In [47]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
p_td = pad_sequences(f_td, maxlen = max_len, padding='pre')

print(p_td)

[[  0   0   0 ...   0   2   3]
 [  0   0   0 ...   2   3   4]
 [  0   0   0 ...   3   4  13]
 ...
 [  0   0   0 ... 188 189   5]
 [  0   0   0 ... 189   5  24]
 [  0   0   0 ...   5  24  25]]


In [48]:
X = p_td[:, :-1]
y = p_td[:, -1]

print(X.shape)
print(y.shape)

(386, 13)
(386,)


In [49]:
y

array([  3,   4,  13,  20,  11,  27,  47,  48,   3,   4,  13,  20,   5,
        49,  50,  28,  51,  52,  53,   3,   4,  13,  20,  21,  27,  54,
        55,   3,   4,  56,   7,  57,  58,  21,  59,  60,  14,  29,  61,
        62,   3,   4,  63,  30,  21,  64,  65,  66,  67,   3,   4,  68,
         6,  31,   7,  69,  32,  33,  30,   3,   4,  70,  15,   7,  71,
        72,  73,   3,   4,  74,   5,   7,  75,  76,  77,  32,   3,   4,
        78,   9,  79,  15,  29,  34,  80,   3,   4,  13,   7,  22,  81,
        82,  14,  83,  35,  16,   3,   4,  84,  85,  33,  35,  16,   3,
         4,  86,   7,  87,  22,  15,  88,  16,  89,   3,   4,  31,  14,
        90,  91,  36,   5,  92,   3,   4,  93,  94,   5,  95,   6,  96,
        16,   3,   4,  97,  98,  99,  12,   9, 100,   3,   4, 101,   7,
        36,  28, 102,   5,  22,   3,   4, 103, 104,   5,   7, 105,   9,
       106,   3,   4,   8,   7,  37, 107,   6,  17,  10, 108,   3,   4,
         8, 109,  18,  38, 110,  39, 111,   3,   4,   8, 112,  1

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [51]:
model = Sequential()
vocab_size = len(tokenizer.word_index) + 1

model.add(Embedding(vocab_size, 100, input_length=13))
model.add(LSTM(150,return_sequences=True))
model.add(LSTM(150))
model.add(Dense(vocab_size, activation='softmax'))

In [52]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [53]:
y = tf.keras.utils.to_categorical(y, num_classes=vocab_size) #ohe
model.fit(X,y,epochs=120)

Epoch 1/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step - accuracy: 0.0743 - loss: 5.1865
Epoch 2/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.1103 - loss: 4.6265
Epoch 3/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.0904 - loss: 4.4929
Epoch 4/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.1667 - loss: 4.2819
Epoch 5/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 93ms/step - accuracy: 0.1453 - loss: 4.1095
Epoch 6/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 93ms/step - accuracy: 0.1482 - loss: 4.1390
Epoch 7/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 92ms/step - accuracy: 0.2322 - loss: 3.9884
Epoch 8/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.2317 - loss: 3.7264
Epoch 9/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.2806 - loss: 3.6539
Epoch 10/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.2531 - loss: 3.5560
Epoch 11/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 0.2962 - loss: 3.4174
Epoch 12/120
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step

In [60]:
text = "antas"

for i in range(10):
  token_text = tokenizer.texts_to_sequences([text])[0]
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
antas kumar
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
antas kumar dubey
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
antas kumar dubey dubey
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
antas kumar dubey dubey is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
antas kumar dubey dubey is works
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
antas kumar dubey dubey is works asks
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
antas kumar dubey dubey is works asks in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
antas kumar dubey dubey is works asks in technical
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
antas kumar dubey dubey is works asks in technical in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
antas kumar dubey dubey is works asks in technical in technical
