<a href="https://colab.research.google.com/github/antas06/DL_Scratch/blob/Root_functions/CNN_forward_stratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.array([
    [1, 2, 0, 1, 2],
    [2, 1, 3, 0, 1],
    [0, 2, 1, 2, 3],
    [1, 0, 2, 1, 0],
    [2, 1, 0, 2, 1]
])

kernel = np.array([
    [1, -1, 1],
    [-1, 1, -1],
    [1, -1, 1]
])


In [5]:

def conv2d(img, kernel):
    k = kernel.shape[0]
    out_h = img.shape[0] - k + 1
    out_w = img.shape[1] - k + 1
    out = np.zeros((out_h, out_w))
    for i in range(out_h):
        for j in range(out_w):
            region = img[i:i+k, j:j+k]
            out[i, j] = np.sum(region * kernel)
    return out

conv_out = conv2d(x, kernel)

relu_out = np.maximum(conv_out, 0)

def maxpool(img, size=2):
    h, w = img.shape
    out_h = h - size + 1
    out_w = w - size + 1
    out = np.zeros((out_h, out_w))
    for i in range(out_h):
        for j in range(out_w):
            region = img[i:i+size, j:j+size]
            out[i, j] = np.max(region)
    return out

pool_out = maxpool(relu_out)

flat = pool_out.flatten()



print("Conv output:\n", conv_out)
print("After ReLU:\n", relu_out)
print("After Pooling:\n", pool_out)
print("Flattened:", flat)


Conv output:
 [[-6.  8. -1.]
 [ 8. -6.  3.]
 [-3.  7.  0.]]
After ReLU:
 [[0. 8. 0.]
 [8. 0. 3.]
 [0. 7. 0.]]
After Pooling:
 [[8. 8.]
 [8. 7.]]
Flattened: [8. 8. 8. 7.]
